#!/bin/bash

### function definitions ###

# print selected date and its tasks
print_day() {
    local date=$1
    
    if [[ $date == $(date +%F) ]]; then
        printf "* "
    fi
    date --date=$date '+%A, %B %d, %Y'
    if [ -f $date ] ; then
        cat -n $date
    fi
    echo
}

# changes the date being used
change_day() {
    exit_status="1"
    while [[ $exit_status != "0" ]]; do
        echo -n "Enter desired day: "
        read input
        date=$(date --date="$input" +%F)
        exit_status=$(echo $?)
    done
}

# adds a new task to the given date
add_task() {
    echo -n ">>> "
    read input
    echo $input >> $date
}

# removes a task from the given date
remove_task() {
    echo -n "Enter line number: "
    read input
    sed -i -e ${input}d $date

    # if all tasks are removed, also delete the date entry
    if [[ $(cat $date) == "" ]]; then
        rm $date
    fi
}

# print all tasks
show_all_tasks() {
    clear
    if [ -z "$(ls .)" ]; then
        echo "All tasks are complete!"
    else
        for date_file in *; do
            print_day $date_file
        done
    fi
    echo "Press enter to continue..."
    read input
}

# directory to store tasks
set_directory() {
    mkdir -p ~/.todos
    cd ~/.todos
}

get_choice() {
    echo -n "(c)hange day; (a)dd task; (r)emove task; (s)how all tasks; (q)uit: "
    read input
}



### main script ###
set_directory
date=$(date +%F)
while [[ $input != "q" ]]; do
    print_day $date
    get_choice
    case $input in
        "c")
            change_day
            ;;
        "a")
            add_task
            ;;
        "r")
            remove_task
            ;;
        "s")
            show_all_tasks
            ;;
    esac
    clear
done